# Qdrant Chunk ID + Section Audit (Per Paper)

This notebook helps you:
- retrieve all chunks for a paper from Qdrant
- print and save chunk IDs
- fetch exact chunk content by IDs
- list all `section_title` values
- print chunks grouped by section title

In [26]:
from pathlib import Path
import os

# Change this to the paper/document identifier you want to inspect.
PAPER_ID = "bd077a96-5a38-5281-993e-10cf869afcde"
PAPER_ID_FIELD = "document_id"
COLLECTION_NAME = os.getenv("QDRANT_COLLECTION", "research_papers")

# Optional limits for quick debugging.
SCROLL_BATCH_SIZE = 256
MAX_POINTS = None  # e.g., 100 for quick checks

PLAYGROUND_DIR = Path.cwd() if Path.cwd().name == "playground" else Path.cwd() / "playground"
PLAYGROUND_DIR.mkdir(parents=True, exist_ok=True)

CHUNK_IDS_JSON = PLAYGROUND_DIR / "chunk_ids.json"
CHUNK_IDS_CSV = PLAYGROUND_DIR / "chunk_ids.csv"
SECTIONS_JSON = PLAYGROUND_DIR / "sections_with_chunks.json"

print(f"Playground dir: {PLAYGROUND_DIR}")
print(f"Collection: {COLLECTION_NAME}")
print(f"Paper ID field: {PAPER_ID_FIELD}")
print(f"Paper ID: {PAPER_ID or '<set me>'}")

Playground dir: /home/aman/storage/Python/Projects/Research Paper Assistant/playground
Collection: research_papers
Paper ID field: document_id
Paper ID: bd077a96-5a38-5281-993e-10cf869afcde

In [27]:
# Install if needed.
%pip install -q qdrant-client pandas

import json
from collections import defaultdict

import pandas as pd
from qdrant_client import QdrantClient
from qdrant_client.models import Filter, FieldCondition, MatchValue

print("Imports ready.")

Note: you may need to restart the kernel to use updated packages.
Imports ready.

In [28]:
# Configure Qdrant connection via env vars.
# Cloud example: export QDRANT_URL='https://...:6333' and QDRANT_API_KEY='...'
# Local example: leave URL empty and set host/port below.
QDRANT_URL = os.getenv("QDRANT_URL", "")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY", "")
QDRANT_HOST = os.getenv("QDRANT_HOST", "localhost")
QDRANT_PORT = int(os.getenv("QDRANT_PORT", "6333"))

if QDRANT_URL:
    client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY or None)
else:
    client = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

collections = client.get_collections()
collection_names = [c.name for c in collections.collections]
print(f"Connected. Collections: {collection_names[:10]}")
if COLLECTION_NAME not in collection_names:
    print(f"Warning: '{COLLECTION_NAME}' not found in current Qdrant instance.")

Connected. Collections: ['research_papers', 'research_papers_main']

In [29]:
if not PAPER_ID:
    raise ValueError("Set PAPER_ID in the setup cell before running this cell.")

all_points = []
offset = None

while True:
    points, next_offset = client.scroll(
        collection_name=COLLECTION_NAME,
        scroll_filter=Filter(
            must=[
                FieldCondition(
                    key=PAPER_ID_FIELD,
                    match=MatchValue(value=PAPER_ID),
                )
            ]
        ),
        limit=SCROLL_BATCH_SIZE,
        with_payload=True,
        with_vectors=False,
        offset=offset,
    )

    if not points:
        break

    all_points.extend(points)

    if MAX_POINTS is not None and len(all_points) >= MAX_POINTS:
        all_points = all_points[:MAX_POINTS]
        break

    if next_offset is None:
        break

    offset = next_offset

chunk_records = []
for p in all_points:
    payload = p.payload if isinstance(p.payload, dict) else {}
    chunk_id = payload.get("chunk_id") or payload.get("_id")
    chunk_records.append(
        {
            "point_id": str(p.id),
            "chunk_id": str(chunk_id) if chunk_id is not None else "",
            "section_title": str(payload.get("section_title") or ""),
            "section_id": str(payload.get("section_id") or ""),
            "content": str(payload.get("content") or ""),
            "payload": payload,
        }
    )

print(f"Fetched points for paper: {PAPER_ID}")
print(f"Total points/chunks found: {len(chunk_records)}")

chunks_df = pd.DataFrame(chunk_records)
chunks_df.head(10)

Fetched points for paper: bd077a96-5a38-5281-993e-10cf869afcde
Total points/chunks found: 96

,point_id,chunk_id,section_title,section_id,content,payload
0,006558f7-0158-59e1-8a44-dea726b2cf43,d19b2017-512e-4fa2-982d-52a2fae7914f,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Diederik Kingma and Jimmy Ba. Adam: A method f...,{'chunk_id': 'd19b2017-512e-4fa2-982d-52a2fae7...
1,0233c58f-c04c-5324-bf84-72532fdc1f24,5f396717-3f09-45e1-a0bc-4918d31729ed,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Smith. Recurrent neural network grammars. In P...,{'chunk_id': '5f396717-3f09-45e1-a0bc-4918d317...
2,0278a119-a01b-539a-903f-65fa986c1bc1,49600c0b-7d12-4f32-b830-832ca2fe2571,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Outrageously large neural networks: The sparse...,{'chunk_id': '49600c0b-7d12-4f32-b830-832ca2fe...
3,033d9657-784e-521f-ae38-8ca7d78fac12,037ff4b1-c31c-4c45-a222-002e9f142edd,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,"ACL, August 2013. Jimmy Lei Ba, Jamie Ryan Kir...",{'chunk_id': '037ff4b1-c31c-4c45-a222-002e9f14...
4,0498359c-e94e-570a-8f23-692256a02687,c9a5f42b-a02a-4880-bd53-6e6ad0f9519f,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,"ACL, June 2006. Ankur Parikh, Oscar Täckström,...",{'chunk_id': 'c9a5f42b-a02a-4880-bd53-6e6ad0f9...
5,07155d70-2e20-54aa-b25e-e6b10f079817,eb1ab886-904c-4829-8743-bf9a43e3763c,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,In Proceedings of the 2009 Conference on Empir...,{'chunk_id': 'eb1ab886-904c-4829-8743-bf9a43e3...
6,0a213754-813f-5499-b38c-1c27e77755b6,5b54d958-e68a-4ae8-b6f0-31fbc2aee1b8,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Smith. Recurrent neural network grammars. In P...,{'chunk_id': '5b54d958-e68a-4ae8-b6f0-31fbc2ae...
7,15fa383b-bc84-5247-a86b-73d1380b2e80,137acc38-0842-498e-bca1-555a8f2b7ec7,Results,bd077a96-5a38-5281-993e-10cf869afcde_section_5,Table 3: Variations on the Transformer archite...,{'chunk_id': '137acc38-0842-498e-bca1-555a8f2b...
8,1937c5f0-a3a0-5230-9fa9-7fbd5af1f033,229c9840-ed46-424f-bce6-062ee059bfa3,Why Self-Attention,bd077a96-5a38-5281-993e-10cf869afcde_section_3,Hence we also compare the maximum path length ...,{'chunk_id': '229c9840-ed46-424f-bce6-062ee059...
9,1a540631-bff4-5989-94df-aae4f6e5a85a,714ec552-cea9-4fc9-8fb5-23d2b8b64e9c,Conclusion,bd077a96-5a38-5281-993e-10cf869afcde_section_6,We are excited about the future of attention-b...,{'chunk_id': '714ec552-cea9-4fc9-8fb5-23d2b8b6...

In [30]:
chunk_ids = [r["chunk_id"] for r in chunk_records if r["chunk_id"]]

print(f"Chunk IDs count: {len(chunk_ids)}")
for i, cid in enumerate(chunk_ids, start=1):
    print(f"{i:04d}: {cid}")

Chunk IDs count: 96
0001: d19b2017-512e-4fa2-982d-52a2fae7914f
0002: 5f396717-3f09-45e1-a0bc-4918d31729ed
0003: 49600c0b-7d12-4f32-b830-832ca2fe2571
0004: 037ff4b1-c31c-4c45-a222-002e9f142edd
0005: c9a5f42b-a02a-4880-bd53-6e6ad0f9519f
0006: eb1ab886-904c-4829-8743-bf9a43e3763c
0007: 5b54d958-e68a-4ae8-b6f0-31fbc2aee1b8
0008: 137acc38-0842-498e-bca1-555a8f2b7ec7
0009: 229c9840-ed46-424f-bce6-062ee059bfa3
0010: 714ec552-cea9-4fc9-8fb5-23d2b8b64e9c
0011: 65af77e8-f870-41ec-b9df-69b18b8eeb23
0012: 213f2272-4aac-491b-9f76-33f99e7c79b2
0013: 3594d1eb-1176-45ab-8ad5-13a7427aa8ba
0014: 392ebb6e-3c8a-441a-b5c6-c3a0e6196b16
0015: f1d90071-a86b-4544-bea1-1fbe62284870
0016: fb2e2ba1-f16d-4147-9b4d-780524152161
0017: e7fff3f6-11b8-42da-a83c-b8be424deb16
0018: dc7dd4f4-6ce0-4f3c-8029-6a78b4a8b87f
0019: 0295a0a2-663d-44d1-8933-f196c6d0a67e
0020: eb7032d2-bbd4-4c7e-a7d5-b83b4dca271d
0021: 5e30fe47-4874-48f0-913f-e9cd607c4281
0022: 5e8b74ca-eb9d-407a-83fb-78bd8f581180
0023: a16354bb-f5fd-43b5-867b-5516217b7168
0024: 0f784d90-4eb2-49af-ad30-4d6aea92e6b0
0025: 32ec363d-7d30-43fa-a74d-ed3b4a55b880
0026: cb32b412-446a-47aa-9afa-65b5a85f958b
0027: a3f7a5aa-f321-421b-92a9-108755c03478
0028: 7c46d454-7a71-4ee1-a448-75959c881528
0029: 149b5811-846d-4671-a114-066ee0e3124e
0030: ac778d3d-3507-4a5e-b3a4-87dc46711525
0031: f6a319f3-c123-4853-afdb-5a31aaf72c87
0032: b017e656-aada-4015-b1ef-bde98fc91385
0033: 035e40d4-e77b-4483-9a68-b9fa83d49dac
0034: 6ad2ccca-3b36-4cc2-935b-201c8edb922e
0035: 3b925835-5fab-44fe-9d50-4ec673427650
0036: dbe1d90d-a9f5-480a-a392-fc069bb8b52c
0037: 3b46f345-6b4c-4e70-911b-e175a57d99f2
0038: eb0ab969-1e72-4b30-810f-372423864206
0039: f1ce755d-a819-47c9-96cf-694ab6e3e6da
0040: 95d449fb-0657-4165-873a-0420b6407597
0041: ed9dbe34-f5b6-4580-a0d4-8df79a27e66b
0042: 72d11f24-46c3-44b1-949a-dddd910bc184
0043: 7ca3885f-bbb6-48ac-aba1-fabe2a62d87b
0044: dc87db97-b36e-4f91-a830-d559921a8999
0045: e44f11a6-4ac5-460e-ae92-7552f14299e4
0046: ce10afc3-7d81-46fd-866e-5bb22bd47c23
0047: 892ed135-337f-416c-8020-ee619e395dc8
0048: aa82269b-5907-405d-8cc1-6f534aed3ea9
0049: 4288f127-65cf-42c2-9bba-5682389e8a11
0050: 9d180bf5-fef0-49b0-b739-3fff89d60052
0051: 089caffa-0f78-454a-b73c-a0e2abfe0439
0052: 24724c38-d666-48fa-9b4c-882297ca9104
0053: 8375d6d9-7653-444a-912f-bce373af0aff
0054: c2770c6b-3f27-4765-95a7-827c2381a228
0055: 46c56101-2eb5-45b3-a9cf-1bb8177f007d
0056: 4ffc09e3-bf7c-45a3-a4d9-684acee3baac
0057: 2459d8e0-e01f-4768-b80f-d75121a57b94
0058: bd824f5a-8ef2-4b4a-b98d-30565baedf79
0059: 4b0d2802-f260-489f-a1be-568b64b076ac
0060: e932a2e3-217d-4613-8e46-ec7aec7b2647
0061: 8149441e-08b5-4ea3-a773-1cb0887b5ac1
0062: a09a0ba8-5893-469e-a5b4-8ae4ce584e34
0063: add191b3-a42d-47d0-b457-d8ee814ce88d
0064: 2f3c2a1c-9413-410a-b485-1c8ebd7beee6
0065: 16edc692-5d59-49f3-b8ae-8289d5b22f8a
0066: 5b7fa2e7-aead-4755-902a-ecf39fea89cc
0067: 58b28a87-31fd-4865-a50d-ed6137576672
0068: c9e796ec-d848-4504-850a-ae7e806c8351
0069: d5fe6599-8673-4dba-94a4-c8b762e38a8e
0070: 8a99a9e4-3336-4591-8e51-956a33e6a06f
0071: 82ed0dc0-017e-4a28-a0ac-f1854910d3a7
0072: 27e7cf82-d905-495a-b7cc-b951b1495248
0073: d9f28871-f979-4676-91bf-8244283c646c
0074: f1eb94a2-2011-4aa0-ba50-3e374fd8543c
0075: bfe2b8fe-cdd4-43b5-b4fa-c68ae425b214
0076: 1150a28c-0a25-4780-9bdc-ad569b8fcc62
0077: e8fa0e4a-4376-4513-8bd8-aa48025c591d
0078: 070f038b-952b-42bb-8d3a-7117f6429d6d
0079: ec5bf2a5-32f3-4bb6-abef-7f14202be7d1
0080: 47d9ad94-71b6-4e56-9f51-a9040ff54d59
0081: 11ef2cee-2fd0-4dd8-a330-413696705b5f
0082: a4d52327-73b7-494a-a635-9cda9cb3dcad
0083: 46f28eef-6880-4ee3-80b7-7d14caeba18e
0084: c9246366-c493-4ce3-a9ac-aecf6e035618
0085: 40fa1f21-fb60-458e-9043-2f194e5f90c7
0086: 31178ce6-b594-41f6-a954-c2f52a206add
0087: 3bfa48e4-aac2-4cb8-8b8a-b65d68bc62ce
0088: 21d37645-b129-4cf9-bf6f-b029961973d1
0089: fe222192-ec48-4225-b93d-574412fcff89
0090: 0034152f-a61e-442f-9ff8-87aa1bdb17f8
0091: 763053fa-632c-44b4-808e-653429bff723
0092: 08e7445b-93d6-4e3c-9f83-50bc2e1deccb
0093: d1af65d5-1d15-43f6-b122-7bc39c93c98b
0094: 5bb2801b-b5de-4f69-b05d-0a83341bfdec
0095: 09b4d3ac-32b3-45fd-911e-8241d828e5dc
0096: 7c00bf85-f12d-4a5f-9765-a9e79715a040

In [31]:
CHUNK_ID_KEY_IN_JSON = "chunk_ids"

CHUNK_IDS_JSON.write_text(
    json.dumps({CHUNK_ID_KEY_IN_JSON: chunk_ids}, indent=2, ensure_ascii=False),
    encoding="utf-8",
)

pd.DataFrame({"chunk_id": chunk_ids}).to_csv(CHUNK_IDS_CSV, index=False)

print(f"Saved JSON: {CHUNK_IDS_JSON}")
print(f"Saved CSV: {CHUNK_IDS_CSV}")

Saved JSON: /home/aman/storage/Python/Projects/Research Paper Assistant/playground/chunk_ids.json
Saved CSV: /home/aman/storage/Python/Projects/Research Paper Assistant/playground/chunk_ids.csv

In [32]:
# Fetch exact content by point IDs from Qdrant (authoritative read).
point_ids = [r["point_id"] for r in chunk_records]

exact_points = []
BATCH = 128
for i in range(0, len(point_ids), BATCH):
    batch = point_ids[i:i + BATCH]
    # Qdrant accepts ids in native format; normalize numeric-looking ids.
    normalized_batch = [int(x) if str(x).isdigit() else x for x in batch]
    exact_points.extend(
        client.retrieve(
            collection_name=COLLECTION_NAME,
            ids=normalized_batch,
            with_payload=True,
            with_vectors=False,
        )
    )

exact_chunk_records = []
for p in exact_points:
    payload = p.payload if isinstance(p.payload, dict) else {}
    chunk_id = payload.get("chunk_id") or payload.get("_id")
    exact_chunk_records.append(
        {
            "point_id": str(p.id),
            "chunk_id": str(chunk_id) if chunk_id is not None else "",
            "section_title": str(payload.get("section_title") or ""),
            "section_id": str(payload.get("section_id") or ""),
            "content": str(payload.get("content") or ""),
            "payload": payload,
        }
    )

exact_df = pd.DataFrame(exact_chunk_records)
print(f"Exact chunks fetched by point_id: {len(exact_chunk_records)}")
exact_df[["point_id", "chunk_id", "section_title", "section_id", "content"]].head(20)

Exact chunks fetched by point_id: 96

,point_id,chunk_id,section_title,section_id,content
0,006558f7-0158-59e1-8a44-dea726b2cf43,d19b2017-512e-4fa2-982d-52a2fae7914f,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Diederik Kingma and Jimmy Ba. Adam: A method f...
1,0233c58f-c04c-5324-bf84-72532fdc1f24,5f396717-3f09-45e1-a0bc-4918d31729ed,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Smith. Recurrent neural network grammars. In P...
2,0278a119-a01b-539a-903f-65fa986c1bc1,49600c0b-7d12-4f32-b830-832ca2fe2571,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Outrageously large neural networks: The sparse...
3,033d9657-784e-521f-ae38-8ca7d78fac12,037ff4b1-c31c-4c45-a222-002e9f142edd,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,"ACL, August 2013. Jimmy Lei Ba, Jamie Ryan Kir..."
4,0498359c-e94e-570a-8f23-692256a02687,c9a5f42b-a02a-4880-bd53-6e6ad0f9519f,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,"ACL, June 2006. Ankur Parikh, Oscar Täckström,..."
5,07155d70-2e20-54aa-b25e-e6b10f079817,eb1ab886-904c-4829-8743-bf9a43e3763c,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,In Proceedings of the 2009 Conference on Empir...
6,0a213754-813f-5499-b38c-1c27e77755b6,5b54d958-e68a-4ae8-b6f0-31fbc2aee1b8,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Smith. Recurrent neural network grammars. In P...
7,15fa383b-bc84-5247-a86b-73d1380b2e80,137acc38-0842-498e-bca1-555a8f2b7ec7,Results,bd077a96-5a38-5281-993e-10cf869afcde_section_5,Table 3: Variations on the Transformer archite...
8,1937c5f0-a3a0-5230-9fa9-7fbd5af1f033,229c9840-ed46-424f-bce6-062ee059bfa3,Why Self-Attention,bd077a96-5a38-5281-993e-10cf869afcde_section_3,Hence we also compare the maximum path length ...
9,1a540631-bff4-5989-94df-aae4f6e5a85a,714ec552-cea9-4fc9-8fb5-23d2b8b64e9c,Conclusion,bd077a96-5a38-5281-993e-10cf869afcde_section_6,We are excited about the future of attention-b...
10,1e10b64b-4be5-5df4-bce6-e4e6d8233265,65af77e8-f870-41ec-b9df-69b18b8eeb23,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,Francois Chollet. Xception: Deep learning with...
11,1f0a78b5-6e61-5a3a-8e54-66b72c450744,213f2272-4aac-491b-9f76-33f99e7c79b2,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,"ACL, July 2006. Ofir Press and Lior Wolf. Usin..."
12,2225487d-c0d1-5060-bdd8-400a29cc18a4,3594d1eb-1176-45ab-8ad5-13a7427aa8ba,Results,bd077a96-5a38-5281-993e-10cf869afcde_section_5,We used a vocabulary of 16K tokens for the WSJ...
13,22c2b14d-1b91-566f-a7e8-58ecf32f4108,392ebb6e-3c8a-441a-b5c6-c3a0e6196b16,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,In Empirical Methods in Natural Language Proce...
14,2420cc8a-76c2-55dd-ac5a-791ae4f6feb6,f1d90071-a86b-4544-bea1-1fbe62284870,Why Self-Attention,bd077a96-5a38-5281-993e-10cf869afcde_section_3,"Even with k = n , however, the complexity of a..."
15,26097fab-9e68-5cbf-ab4f-1c99940ddd05,fb2e2ba1-f16d-4147-9b4d-780524152161,Background,bd077a96-5a38-5281-993e-10cf869afcde_section_1,End-to-end memory networks are based on a recu...
16,273e1ffa-4374-5436-acab-3be7ad55351a,e7fff3f6-11b8-42da-a83c-b8be424deb16,Background,bd077a96-5a38-5281-993e-10cf869afcde_section_1,This makes it more difficult to learn dependen...
17,27e6f357-04ad-5258-be67-8b458ed5e211,dc7dd4f4-6ce0-4f3c-8029-6a78b4a8b87f,Model Architecture,bd077a96-5a38-5281-993e-10cf869afcde_section_2,Most competitive neural sequence transduction ...
18,2d1c67d5-a9ce-514e-aef4-c19aeccd2e4a,0295a0a2-663d-44d1-8933-f196c6d0a67e,Results,bd077a96-5a38-5281-993e-10cf869afcde_section_5,We used a vocabulary of 16K tokens for the WSJ...
19,2d2055a8-d161-54b0-8bbf-a6e962c34f58,eb7032d2-bbd4-4c7e-a7d5-b83b4dca271d,Reference,bd077a96-5a38-5281-993e-10cf869afcde_section_7,"CoRR , abs/1703.03906, 2017. Jianpeng Cheng, L..."

In [33]:
section_titles = sorted({str(r.get("section_title") or "").strip() for r in exact_chunk_records})
non_empty_section_titles = [s for s in section_titles if s]
missing_section_title_count = sum(1 for r in exact_chunk_records if not str(r.get("section_title") or "").strip())

print(f"Unique non-empty section_title values: {len(non_empty_section_titles)}")
for title in non_empty_section_titles:
    print(f"- {title}")

print(f"Chunks with missing/empty section_title: {missing_section_title_count}")

Unique non-empty section_title values: 7
- Background
- Conclusion
- Introduction
- Model Architecture
- Reference
- Results
- Why Self-Attention
Chunks with missing/empty section_title: 0

In [34]:
grouped = defaultdict(list)
for rec in exact_chunk_records:
    key = str(rec.get("section_title") or "<MISSING_SECTION_TITLE>").strip() or "<MISSING_SECTION_TITLE>"
    grouped[key].append(rec)

section_export = {}
for section in sorted(grouped.keys()):
    rows = sorted(grouped[section], key=lambda x: (x.get("chunk_id", ""), x.get("point_id", "")))
    section_export[section] = [
        {
            "point_id": r["point_id"],
            "chunk_id": r["chunk_id"],
            "section_id": r["section_id"],
            "content": r["content"],
        }
        for r in rows
    ]

print(f"Sections found: {len(section_export)}")
for section, rows in section_export.items():
    print("\n" + "=" * 80)
    print(f"Section: {section} | chunks: {len(rows)}")
    print("=" * 80)
    for i, row in enumerate(rows, start=1):
        preview = " ".join(str(row["content"]).split())[:220]
        if len(str(row["content"])) > 220:
            preview += "..."
        print(f"{i:03d}. chunk_id={row['chunk_id']} | point_id={row['point_id']} | section_id={row['section_id']}")
        print(f"     content: {preview}")

SECTIONS_JSON.write_text(json.dumps(section_export, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"\nSaved grouped output: {SECTIONS_JSON}")

Sections found: 7

================================================================================
Section: Background | chunks: 6
================================================================================
001. chunk_id=3b46f345-6b4c-4e70-911b-e175a57d99f2 | point_id=60fb01ba-6c8a-53d0-80c2-7f0ca297057f | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_1
     content: Figure 1: The Transformer - model architecture.
002. chunk_id=8375d6d9-7653-444a-912f-bce373af0aff | point_id=8753155a-22db-5b6f-a825-959fa533081c | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_1
     content: The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building block, computing hidde...
003. chunk_id=a09a0ba8-5893-469e-a5b4-8ae4ce584e34 | point_id=a00a1b27-b1d5-5a6c-ab7b-9186fc86ba6f | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_1
     content: The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building block, computing hidde...
004. chunk_id=e7fff3f6-11b8-42da-a83c-b8be424deb16 | point_id=273e1ffa-4374-5436-acab-3be7ad55351a | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_1
     content: This makes it more difficult to learn dependencies between distant positions [12]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averagin...
005. chunk_id=f1eb94a2-2011-4aa0-ba50-3e374fd8543c | point_id=c2b4ddb2-3d34-54c9-bd4a-5bf89a623259 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_1
     content: Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel.
006. chunk_id=fb2e2ba1-f16d-4147-9b4d-780524152161 | point_id=26097fab-9e68-5cbf-ab4f-1c99940ddd05 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_1
     content: End-to-end memory networks are based on a recurrent attention mechanism instead of sequencealigned recurrence and have been shown to perform well on simple-language question answering and language modeling tasks [34]. To...

================================================================================
Section: Conclusion | chunks: 4
================================================================================
001. chunk_id=149b5811-846d-4671-a114-066ee0e3124e | point_id=46fe2449-ce36-5148-aba6-a01532a24e91 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_6
     content: The table compares the performance of various parsers on English constituency parsing. The parsers were trained using different methods and evaluated on the WSJ 23 dataset. The results show that discriminative training o...
002. chunk_id=5bb2801b-b5de-4f69-b05d-0a83341bfdec | point_id=f7bcdbe8-23ec-5a56-b93c-f22d0251e7fb | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_6
     content: In this work, we presented the Transformer, the first sequence transduction model based entirely on attention, replacing the recurrent layers most commonly used in encoder-decoder architectures with multi-headed self-att...
003. chunk_id=714ec552-cea9-4fc9-8fb5-23d2b8b64e9c | point_id=1a540631-bff4-5989-94df-aae4f6e5a85a | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_6
     content: We are excited about the future of attention-based models and plan to apply them to other tasks. We plan to extend the Transformer to problems involving input and output modalities other than text and to investigate loca...
004. chunk_id=82ed0dc0-017e-4a28-a0ac-f1854910d3a7 | point_id=bc5af490-352e-5322-81c5-006f4e8881e9 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_6
     content: In this work, we presented the Transformer, the first sequence transduction model based entirely on attention, replacing the recurrent layers most commonly used in encoder-decoder architectures with multi-headed self-att...

================================================================================
Section: Introduction | chunks: 6
================================================================================
001. chunk_id=09b4d3ac-32b3-45fd-911e-8241d828e5dc | point_id=f969e3c4-60fe-57ba-afb0-be5080ad991d | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_0
     content: Figure 1: The Transformer - model architecture.
002. chunk_id=5e30fe47-4874-48f0-913f-e9cd607c4281 | point_id=33b359e5-4981-512d-beb1-79a6a8790f1f | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_0
     content: In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network. In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying ent...
003. chunk_id=7c00bf85-f12d-4a5f-9765-a9e79715a040 | point_id=fd71574d-d628-5376-ab4f-feef4d063f35 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_0
     content: Recurrent neural networks, long short-term memory [13] and gated recurrent [7] neural networks in particular, have been firmly established as state of the art approaches in sequence modeling and transduction problems suc...
004. chunk_id=95d449fb-0657-4165-873a-0420b6407597 | point_id=66e75ba7-2649-5741-b2f5-f91a6400942c | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_0
     content: Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel.
005. chunk_id=b017e656-aada-4015-b1ef-bde98fc91385 | point_id=4edcc69c-20a1-5a88-bb11-8e3a60981446 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_0
     content: This inherently sequential nature precludes parallelization within training examples, which becomes critical at longer sequence lengths, as memory constraints limit batching across examples. Recent work has achieved sign...
006. chunk_id=c9e796ec-d848-4504-850a-ae7e806c8351 | point_id=b6805637-e46e-5bf4-bbd0-e94e0be229e4 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_0
     content: Recurrent neural networks, long short-term memory [13] and gated recurrent [7] neural networks in particular, have been firmly established as state of the art approaches in sequence modeling and transduction problems suc...

================================================================================
Section: Model Architecture | chunks: 5
================================================================================
001. chunk_id=1150a28c-0a25-4780-9bdc-ad569b8fcc62 | point_id=c7e04168-38fc-52f8-84e2-d22f3ee2bc83 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_2
     content: At each step the model is auto-regressive [10], consuming the previously generated symbols as additional input when generating the next. The Transformer follows this overall architecture using stacked self-attention and ...
002. chunk_id=763053fa-632c-44b4-808e-653429bff723 | point_id=f46bb636-a362-5857-b688-3191bf56ddd4 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_2
     content: Figure 1: The Transformer - model architecture.
003. chunk_id=dc7dd4f4-6ce0-4f3c-8029-6a78b4a8b87f | point_id=27e6f357-04ad-5258-be67-8b458ed5e211 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_2
     content: Most competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 35]. Here, the encoder maps an input sequence of symbol representations ( x 1 , ..., x n ) to a sequence of continuous represe...
004. chunk_id=dc87db97-b36e-4f91-a830-d559921a8999 | point_id=72662b14-fb52-55e8-90e9-ffb5aec704cb | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_2
     content: Figure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several attention layers running in parallel.
005. chunk_id=e44f11a6-4ac5-460e-ae92-7552f14299e4 | point_id=736bfecf-d4ca-5590-98b7-54bcf9cd6bfc | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_2
     content: Most competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 35]. Here, the encoder maps an input sequence of symbol representations ( x 1 , ..., x n ) to a sequence of continuous represe...

================================================================================
Section: Reference | chunks: 45
================================================================================
001. chunk_id=0034152f-a61e-442f-9ff8-87aa1bdb17f8 | point_id=e9208ba8-5b0c-5eb6-bfcb-3e6fa3e61434 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: End-to-end memory networks. In C. Cortes, N. D. Lawrence, D. D. Lee, M. Sugiyama, and R. Garnett, editors, Advances in Neural Information Processing Systems 28 , pages 2440-2448. Curran Associates, Inc., 2015. Ilya Sutsk...
002. chunk_id=037ff4b1-c31c-4c45-a222-002e9f142edd | point_id=033d9657-784e-521f-ae38-8ca7d78fac12 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: ACL, August 2013. Jimmy Lei Ba, Jamie Ryan Kiros, and Geoffrey E Hinton. Layer normalization. arXiv preprint arXiv:1607.06450 , 2016. Dzmitry Bahdanau, Kyunghyun Cho, and Yoshua Bengio. Neural machine translation by join...
003. chunk_id=070f038b-952b-42bb-8d3a-7117f6429d6d | point_id=ca12e833-ac7c-5f09-88b1-8e9986c274f8 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Le. Massive exploration of neural machine translation architectures. CoRR , abs/1703.03906, 2017. Jianpeng Cheng, Li Dong, and Mirella Lapata. Long short-term memory-networks for machine reading. arXiv preprint arXiv:160...
004. chunk_id=089caffa-0f78-454a-b73c-a0e2abfe0439 | point_id=85d6a996-0a8a-5e6e-a050-575f3d312071 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Effective approaches to attentionbased neural machine translation. arXiv preprint arXiv:1508.04025 , 2015. Mitchell P Marcus, Mary Ann Marcinkiewicz, and Beatrice Santorini. Building a large annotated corpus of english: ...
005. chunk_id=08e7445b-93d6-4e3c-9f83-50bc2e1deccb | point_id=f5faa1e7-6a10-550a-8a49-ded15206a4ec | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: CoRR , abs/1703.03906, 2017. Jianpeng Cheng, Li Dong, and Mirella Lapata. Long short-term memory-networks for machine reading. arXiv preprint arXiv:1601.06733 , 2016. Kyunghyun Cho, Bart van Merrienboer, Caglar Gulcehre,...
006. chunk_id=0f784d90-4eb2-49af-ad30-4d6aea92e6b0 | point_id=3e9b4bea-9580-5e1d-911a-d6a7517dd7e5 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Łukasz Kaiser and Ilya Sutskever. Neural GPUs learn algorithms. In International Conference on Learning Representations (ICLR) , 2016. Nal Kalchbrenner, Lasse Espeholt, Karen Simonyan, Aaron van den Oord, Alex Graves, an...
007. chunk_id=16edc692-5d59-49f3-b8ae-8289d5b22f8a | point_id=ac9b9b62-dece-530e-8101-dd695bd49da5 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: arXiv preprint arXiv:1609.08144 , 2016. Jie Zhou, Ying Cao, Xuguang Wang, Peng Li, and Wei Xu. Deep recurrent models with fast-forward connections for neural machine translation. CoRR , abs/1606.04199, 2016. Muhua Zhu, Y...
008. chunk_id=213f2272-4aac-491b-9f76-33f99e7c79b2 | point_id=1f0a78b5-6e61-5a3a-8e54-66b72c450744 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: ACL, July 2006. Ofir Press and Lior Wolf. Using the output embedding to improve language models. arXiv preprint arXiv:1608.05859 , 2016. Rico Sennrich, Barry Haddow, and Alexandra Birch. Neural machine translation of rar...
009. chunk_id=24724c38-d666-48fa-9b4c-882297ca9104 | point_id=86760003-9df1-5a19-ac9e-274068c607f5 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Smith. Recurrent neural network grammars. In Proc. of NAACL , 2016. Jonas Gehring, Michael Auli, David Grangier, Denis Yarats, and Yann N. Dauphin. Convolutional sequence to sequence learning. arXiv preprint arXiv:1705.0...
010. chunk_id=2f3c2a1c-9413-410a-b485-1c8ebd7beee6 | point_id=a4199cfb-8a44-5222-8eaf-38b1f8dc1061 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Deep residual learning for image recognition. In Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition , pages 770-778, 2016. Sepp Hochreiter, Yoshua Bengio, Paolo Frasconi, and Jürgen Schmidhuber...
011. chunk_id=32ec363d-7d30-43fa-a74d-ed3b4a55b880 | point_id=3f70b604-985f-5bd7-94fb-aaa9e825d7c7 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Łukasz Kaiser and Ilya Sutskever. Neural GPUs learn algorithms. In International Conference on Learning Representations (ICLR) , 2016. Nal Kalchbrenner, Lasse Espeholt, Karen Simonyan, Aaron van den Oord, Alex Graves, an...
012. chunk_id=392ebb6e-3c8a-441a-b5c6-c3a0e6196b16 | point_id=22c2b14d-1b91-566f-a7e8-58ecf32f4108 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: In Empirical Methods in Natural Language Processing , 2016. Romain Paulus, Caiming Xiong, and Richard Socher. A deep reinforced model for abstractive summarization. arXiv preprint arXiv:1705.04304 , 2017. Slav Petrov, Le...
013. chunk_id=3b925835-5fab-44fe-9d50-4ec673427650 | point_id=5638a5ea-c125-50f1-87fb-ee8be40d4a62 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: ACL, July 2006. Ofir Press and Lior Wolf. Using the output embedding to improve language models. arXiv preprint arXiv:1608.05859 , 2016. Rico Sennrich, Barry Haddow, and Alexandra Birch. Neural machine translation of rar...
014. chunk_id=40fa1f21-fb60-458e-9043-2f194e5f90c7 | point_id=da44d62e-9bef-5c58-b357-ad02a3ba5c16 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: arXiv preprint arXiv:1703.03130 , 2017. Minh-Thang Luong, Quoc V. Le, Ilya Sutskever, Oriol Vinyals, and Lukasz Kaiser. Multi-task sequence to sequence learning. arXiv preprint arXiv:1511.06114 , 2015. Minh-Thang Luong, ...
015. chunk_id=46c56101-2eb5-45b3-a9cf-1bb8177f007d | point_id=93b1802a-256c-504a-bc55-6ee522da762d | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Rethinking the inception architecture for computer vision. CoRR , abs/1512.00567, 2015. Vinyals & Kaiser, Koo, Petrov, Sutskever, and Hinton. Grammar as a foreign language. In Advances in Neural Information Processing Sy...
016. chunk_id=47d9ad94-71b6-4e56-9f51-a9040ff54d59 | point_id=cbb779e8-5f54-5b5d-9c5e-24d6ec617ada | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: arXiv preprint arXiv:1703.03130 , 2017. Minh-Thang Luong, Quoc V. Le, Ilya Sutskever, Oriol Vinyals, and Lukasz Kaiser. Multi-task sequence to sequence learning. arXiv preprint arXiv:1511.06114 , 2015. Minh-Thang Luong, ...
017. chunk_id=49600c0b-7d12-4f32-b830-832ca2fe2571 | point_id=0278a119-a01b-539a-903f-65fa986c1bc1 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Outrageously large neural networks: The sparsely-gated mixture-of-experts layer. arXiv preprint arXiv:1701.06538 , 2017. Nitish Srivastava, Geoffrey E Hinton, Alex Krizhevsky, Ilya Sutskever, and Ruslan Salakhutdinov. Dr...
018. chunk_id=4ffc09e3-bf7c-45a3-a4d9-684acee3baac | point_id=94df6309-4c40-5ad7-8389-02ba516a8cbf | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: In Proceedings of the 2009 Conference on Empirical Methods in Natural Language Processing , pages 832-841. ACL, August 2009. Rafal Jozefowicz, Oriol Vinyals, Mike Schuster, Noam Shazeer, and Yonghui Wu. Exploring the lim...
019. chunk_id=58b28a87-31fd-4865-a50d-ed6137576672 | point_id=b2d2dc1a-29d2-586e-afa0-9d39c565c00d | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Jimmy Lei Ba, Jamie Ryan Kiros, and Geoffrey E Hinton. Layer normalization. arXiv preprint arXiv:1607.06450 , 2016. Dzmitry Bahdanau, Kyunghyun Cho, and Yoshua Bengio. Neural machine translation by jointly learning to al...
020. chunk_id=5b54d958-e68a-4ae8-b6f0-31fbc2aee1b8 | point_id=0a213754-813f-5499-b38c-1c27e77755b6 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Smith. Recurrent neural network grammars. In Proc. of NAACL , 2016. Jonas Gehring, Michael Auli, David Grangier, Denis Yarats, and Yann N. Dauphin. Convolutional sequence to sequence learning. arXiv preprint arXiv:1705.0...
021. chunk_id=5b7fa2e7-aead-4755-902a-ecf39fea89cc | point_id=ad412ade-25a0-5e45-a60d-65b980f43d92 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Francois Chollet. Xception: Deep learning with depthwise separable convolutions. arXiv preprint arXiv:1610.02357 , 2016. Junyoung Chung, Çaglar Gülçehre, Kyunghyun Cho, and Yoshua Bengio. Empirical evaluation of gated re...
022. chunk_id=5f396717-3f09-45e1-a0bc-4918d31729ed | point_id=0233c58f-c04c-5324-bf84-72532fdc1f24 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Smith. Recurrent neural network grammars. In Proc. of NAACL , 2016. Jonas Gehring, Michael Auli, David Grangier, Denis Yarats, and Yann N. Dauphin. Convolutional sequence to sequence learning. arXiv preprint arXiv:1705.0...
023. chunk_id=65af77e8-f870-41ec-b9df-69b18b8eeb23 | point_id=1e10b64b-4be5-5df4-bce6-e4e6d8233265 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Francois Chollet. Xception: Deep learning with depthwise separable convolutions. arXiv preprint arXiv:1610.02357 , 2016. Junyoung Chung, Çaglar Gülçehre, Kyunghyun Cho, and Yoshua Bengio. Empirical evaluation of gated re...
024. chunk_id=72d11f24-46c3-44b1-949a-dddd910bc184 | point_id=6f0d02c5-8f0c-5bb4-a693-cb8a844fcc96 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Yoon Kim, Carl Denton, Luong Hoang, and Alexander M. Rush. Structured attention networks. In International Conference on Learning Representations , 2017. Diederik Kingma and Jimmy Ba. Adam: A method for stochastic optimi...
025. chunk_id=8149441e-08b5-4ea3-a773-1cb0887b5ac1 | point_id=9ec7178a-b85f-5041-aac7-8dac69b9f584 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: In Empirical Methods in Natural Language Processing , 2016. Romain Paulus, Caiming Xiong, and Richard Socher. A deep reinforced model for abstractive summarization. arXiv preprint arXiv:1705.04304 , 2017. Slav Petrov, Le...
026. chunk_id=892ed135-337f-416c-8020-ee619e395dc8 | point_id=7848dd75-87ba-5d66-a818-443260f981ee | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Deep residual learning for image recognition. In Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition , pages 770-778, 2016. Sepp Hochreiter, Yoshua Bengio, Paolo Frasconi, and Jürgen Schmidhuber...
027. chunk_id=a3f7a5aa-f321-421b-92a9-108755c03478 | point_id=42ebde18-b6f3-5d30-be83-66695be00c7a | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: Mitchell P Marcus, Mary Ann Marcinkiewicz, and Beatrice Santorini. Building a large annotated corpus of english: The penn treebank. Computational linguistics , 19(2):313-330, 1993. David McClosky, Eugene Charniak, and Ma...
028. chunk_id=a4d52327-73b7-494a-a635-9cda9cb3dcad | point_id=d233c2b6-5d0b-5846-8abc-33b1a4c61715 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7
     content: The table compares the performance of various parsers on the task of English constituency parsing, specifically on Section 23 of the Wall Street Journal (WSJ). The parsers were trained using different methods and evaluat...
029. chunk_id=aa82269b-5907-405d-8cc1-6f534aed3ea9 | point_id=796bf3d8-7206-5a93-ae02-413ac5e6e5e6 | section_id=bd077a96-5a38-5281-993e-10cf869afcde_section_7